object frPedidosAddProduto: TfrPedidosAddProduto
  Left = 0
  Top = 0
  Caption = 'Adicionar'
  ClientHeight = 204
  ClientWidth = 364
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  KeyPreview = True
  OldCreateOrder = False
  Position = poScreenCenter
  PixelsPerInch = 96
  TextHeight = 13
  object Label1: TLabel
    AlignWithMargins = True
    Left = 10
    Top = 10
    Width = 351
    Height = 13
    Margins.Left = 10
    Margins.Top = 10
    Margins.Bottom = 0
    Align = alTop
    Caption = 'ID:'
    ExplicitWidth = 15
  end
  object Label3: TLabel
    AlignWithMargins = True
    Left = 10
    Top = 110
    Width = 351
    Height = 13
    Margins.Left = 10
    Margins.Top = 10
    Margins.Bottom = 0
    Align = alTop
    Caption = 'Qtde:'
    ExplicitTop = 115
    ExplicitWidth = 28
  end
  object Label4: TLabel
    AlignWithMargins = True
    Left = 10
    Top = 60
    Width = 351
    Height = 13
    Margins.Left = 10
    Margins.Top = 10
    Margins.Bottom = 0
    Align = alTop
    Caption = 'Produto:'
    ExplicitTop = 65
    ExplicitWidth = 42
  end
  object Panel2: TPanel
    Left = 0
    Top = 154
    Width = 364
    Height = 50
    Align = alBottom
    BevelOuter = bvNone
    TabOrder = 0
    object Button2: TButton
      AlignWithMargins = True
      Left = 276
      Top = 1
      Width = 85
      Height = 47
      Margins.Left = 1
      Margins.Top = 1
      Margins.Bottom = 2
      Align = alRight
      Caption = 'Fechar'
      TabOrder = 0
      OnClick = Button2Click
    end
    object Button10: TButton
      AlignWithMargins = True
      Left = 189
      Top = 1
      Width = 85
      Height = 47
      Margins.Left = 1
      Margins.Top = 1
      Margins.Right = 1
      Margins.Bottom = 2
      Align = alRight
      Caption = 'Gravar'
      TabOrder = 1
      OnClick = Button10Click
    end
  end
  object edQtde: TEdit
    AlignWithMargins = True
    Left = 10
    Top = 126
    Width = 351
    Height = 21
    Margins.Left = 10
    Align = alTop
    TabOrder = 1
    ExplicitTop = 131
  end
  object edID: TEdit
    AlignWithMargins = True
    Left = 10
    Top = 26
    Width = 351
    Height = 21
    Margins.Left = 10
    Align = alTop
    Color = 15987699
    Enabled = False
    TabOrder = 2
  end
  object dblProduto: TDBLookupComboBox
    AlignWithMargins = True
    Left = 10
    Top = 76
    Width = 351
    Height = 21
    Margins.Left = 10
    Align = alTop
    TabOrder = 3
    OnKeyDown = dblProdutoKeyDown
  end
end
