object frProdutoNovo: TfrProdutoNovo
  Left = 0
  Top = 0
  BorderStyle = bsDialog
  Caption = 'Produto'
  ClientHeight = 271
  ClientWidth = 378
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  Position = poMainFormCenter
  PixelsPerInch = 96
  TextHeight = 13
  object Label1: TLabel
    AlignWithMargins = True
    Left = 10
    Top = 10
    Width = 365
    Height = 13
    Margins.Left = 10
    Margins.Top = 10
    Margins.Bottom = 0
    Align = alTop
    Caption = 'ID:'
    ExplicitWidth = 15
  end
  object Label2: TLabel
    AlignWithMargins = True
    Left = 10
    Top = 160
    Width = 365
    Height = 13
    Margins.Left = 10
    Margins.Top = 10
    Margins.Bottom = 0
    Align = alTop
    Caption = 'Valor:'
    ExplicitTop = 175
    ExplicitWidth = 28
  end
  object Label3: TLabel
    AlignWithMargins = True
    Left = 10
    Top = 110
    Width = 365
    Height = 13
    Margins.Left = 10
    Margins.Top = 10
    Margins.Bottom = 0
    Align = alTop
    Caption = 'Descri'#231#227'o:'
    ExplicitTop = 120
    ExplicitWidth = 50
  end
  object Label4: TLabel
    AlignWithMargins = True
    Left = 10
    Top = 60
    Width = 365
    Height = 13
    Margins.Left = 10
    Margins.Top = 10
    Margins.Bottom = 0
    Align = alTop
    Caption = 'C'#243'digo:'
    ExplicitTop = 65
    ExplicitWidth = 37
  end
  object Panel2: TPanel
    Left = 0
    Top = 221
    Width = 378
    Height = 50
    Align = alBottom
    BevelOuter = bvNone
    TabOrder = 0
    object btFechar: TButton
      AlignWithMargins = True
      Left = 290
      Top = 1
      Width = 85
      Height = 47
      Margins.Left = 1
      Margins.Top = 1
      Margins.Bottom = 2
      Align = alRight
      Caption = 'Fechar'
      TabOrder = 0
      OnClick = btFecharClick
    end
    object btGravar: TButton
      AlignWithMargins = True
      Left = 203
      Top = 1
      Width = 85
      Height = 47
      Margins.Left = 1
      Margins.Top = 1
      Margins.Right = 1
      Margins.Bottom = 2
      Align = alRight
      Caption = 'Gravar'
      TabOrder = 1
      OnClick = btGravarClick
    end
  end
  object Edit1: TEdit
    AlignWithMargins = True
    Left = 10
    Top = 126
    Width = 365
    Height = 21
    Margins.Left = 10
    Align = alTop
    TabOrder = 1
    ExplicitTop = 136
  end
  object Edit2: TEdit
    AlignWithMargins = True
    Left = 10
    Top = 176
    Width = 365
    Height = 21
    Margins.Left = 10
    Align = alTop
    TabOrder = 2
    ExplicitTop = 186
  end
  object Edit3: TEdit
    AlignWithMargins = True
    Left = 10
    Top = 26
    Width = 365
    Height = 21
    Margins.Left = 10
    Align = alTop
    Color = 15987699
    Enabled = False
    TabOrder = 3
  end
  object Edit4: TEdit
    AlignWithMargins = True
    Left = 10
    Top = 76
    Width = 365
    Height = 21
    Margins.Left = 10
    Align = alTop
    TabOrder = 4
  end
end
