object frUsuarioNovo: TfrUsuarioNovo
  Left = 0
  Top = 0
  BorderStyle = bsDialog
  Caption = 'Usu'#225'rio'
  ClientHeight = 271
  ClientWidth = 319
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  KeyPreview = True
  OldCreateOrder = False
  Position = poScreenCenter
  OnKeyDown = FormKeyDown
  PixelsPerInch = 96
  TextHeight = 13
  object Label1: TLabel
    AlignWithMargins = True
    Left = 10
    Top = 10
    Width = 306
    Height = 13
    Margins.Left = 10
    Margins.Top = 10
    Margins.Bottom = 0
    Align = alTop
    Caption = 'ID:'
    ExplicitWidth = 15
  end
  object Label2: TLabel
    AlignWithMargins = True
    Left = 10
    Top = 175
    Width = 306
    Height = 13
    Margins.Left = 10
    Margins.Top = 10
    Margins.Bottom = 0
    Align = alTop
    Caption = 'Senha:'
    ExplicitWidth = 34
  end
  object Label3: TLabel
    AlignWithMargins = True
    Left = 10
    Top = 120
    Width = 306
    Height = 13
    Margins.Left = 10
    Margins.Top = 10
    Margins.Bottom = 0
    Align = alTop
    Caption = 'Usu'#225'rio'
    ExplicitWidth = 36
  end
  object Label4: TLabel
    AlignWithMargins = True
    Left = 10
    Top = 65
    Width = 306
    Height = 13
    Margins.Left = 10
    Margins.Top = 10
    Margins.Bottom = 0
    Align = alTop
    Caption = 'Nome:'
    ExplicitWidth = 31
  end
  object Panel2: TPanel
    Left = 0
    Top = 221
    Width = 319
    Height = 50
    Align = alBottom
    BevelOuter = bvNone
    TabOrder = 0
    ExplicitTop = 249
    ExplicitWidth = 580
    object btFechar: TButton
      AlignWithMargins = True
      Left = 231
      Top = 1
      Width = 85
      Height = 47
      Margins.Left = 1
      Margins.Top = 1
      Margins.Bottom = 2
      Align = alRight
      Caption = 'Fechar'
      TabOrder = 0
      OnClick = btFecharClick
      ExplicitLeft = 290
    end
    object btGravar: TButton
      AlignWithMargins = True
      Left = 144
      Top = 1
      Width = 85
      Height = 47
      Margins.Left = 1
      Margins.Top = 1
      Margins.Right = 1
      Margins.Bottom = 2
      Align = alRight
      Caption = 'Gravar'
      TabOrder = 1
      OnClick = btGravarClick
      ExplicitLeft = 203
    end
  end
  object Edit1: TEdit
    AlignWithMargins = True
    Left = 10
    Top = 136
    Width = 306
    Height = 26
    Margins.Left = 10
    Align = alTop
    TabOrder = 1
    ExplicitWidth = 622
  end
  object Edit2: TEdit
    AlignWithMargins = True
    Left = 10
    Top = 191
    Width = 306
    Height = 26
    Margins.Left = 10
    Align = alTop
    TabOrder = 2
    ExplicitWidth = 622
  end
  object Edit3: TEdit
    AlignWithMargins = True
    Left = 10
    Top = 26
    Width = 306
    Height = 26
    Margins.Left = 10
    Align = alTop
    Color = 15987699
    Enabled = False
    TabOrder = 3
    ExplicitWidth = 622
  end
  object Edit4: TEdit
    AlignWithMargins = True
    Left = 10
    Top = 81
    Width = 306
    Height = 26
    Margins.Left = 10
    Align = alTop
    TabOrder = 4
    ExplicitWidth = 622
  end
end
